/**
 * Supplemental MITRE ATT&CK technique name/tactic lookup for techniques referenced
 * by imported rules (via attack.* tags) but not part of the curated seed set in mitre.ts.
 *
 * Sourced from the official MITRE ATT&CK STIX data (Enterprise, ICS, Mobile domains).
 * Used by ensureMitreTechniques() in importers/runner.ts to populate accurate
 * name/tactic values instead of an "Unmapped" placeholder when auto-seeding
 * FK rows for technique IDs encountered during import.
 */
export const mitreExtraTechniques: Record<string, { name: string; tactic: string }> = {
  "T0806": { name: "Brute Force I/O", tactic: "Impact" },
  "T0813": { name: "Denial of Control", tactic: "Impact" },
  "T0814": { name: "Denial of Service", tactic: "Impact" },
  "T0816": { name: "Device Restart/Shutdown", tactic: "Impact" },
  "T0819": { name: "Exploit Public-Facing Application", tactic: "Initial Access" },
  "T0822": { name: "External Remote Services", tactic: "Initial Access" },
  "T0826": { name: "Loss of Availability", tactic: "Impact" },
  "T0827": { name: "Loss of Control", tactic: "Impact" },
  "T0828": { name: "Loss of Productivity and Revenue", tactic: "Impact" },
  "T0830": { name: "Adversary-in-the-Middle", tactic: "Collection" },
  "T0831": { name: "Manipulation of Control", tactic: "Impact" },
  "T0834": { name: "Native API", tactic: "Execution" },
  "T0836": { name: "Modify Parameter", tactic: "Impact" },
  "T0837": { name: "Loss of Protection", tactic: "Impact" },
  "T0839": { name: "Module Firmware", tactic: "Persistence" },
  "T0840": { name: "Network Connection Enumeration", tactic: "Discovery" },
  "T0842": { name: "Network Sniffing", tactic: "Discovery" },
  "T0843": { name: "Program Download", tactic: "Lateral Movement" },
  "T0845": { name: "Program Upload", tactic: "Collection" },
  "T0846": { name: "Remote System Discovery", tactic: "Discovery" },
  "T0848": { name: "Rogue Master", tactic: "Initial Access" },
  "T0851": { name: "Rootkit", tactic: "Defense Evasion" },
  "T0853": { name: "Scripting", tactic: "Execution" },
  "T0855": { name: "Command Message", tactic: "Defense Evasion" },
  "T0857": { name: "System Firmware", tactic: "Persistence" },
  "T0858": { name: "Change Operating Mode", tactic: "Execution" },
  "T0859": { name: "Valid Accounts", tactic: "Persistence" },
  "T0862": { name: "Supply Chain Compromise", tactic: "Initial Access" },
  "T0863": { name: "User Execution", tactic: "Execution" },
  "T0865": { name: "Spearphishing Attachment", tactic: "Initial Access" },
  "T0866": { name: "Exploitation of Remote Services", tactic: "Initial Access" },
  "T0871": { name: "Execution through API", tactic: "Execution" },
  "T0873": { name: "Project File Infection", tactic: "Persistence" },
  "T0879": { name: "Damage to Property", tactic: "Impact" },
  "T0881": { name: "Service Stop", tactic: "Impact" },
  "T0882": { name: "Theft of Operational Information", tactic: "Impact" },
  "T0883": { name: "Internet Accessible Device", tactic: "Initial Access" },
  "T0885": { name: "Commonly Used Port", tactic: "Command and Control" },
  "T0886": { name: "Remote Services", tactic: "Initial Access" },
  "T0888": { name: "Remote System Information Discovery", tactic: "Discovery" },
  "T0889": { name: "Modify Program", tactic: "Persistence" },
  "T0890": { name: "Exploitation for Privilege Escalation", tactic: "Privilege Escalation" },
  "T1001": { name: "Data Obfuscation", tactic: "Command and Control" },
  "T1001.003": { name: "Protocol or Service Impersonation", tactic: "Command and Control" },
  "T1003.003": { name: "NTDS", tactic: "Credential Access" },
  "T1003.004": { name: "LSA Secrets", tactic: "Credential Access" },
  "T1003.005": { name: "Cached Domain Credentials", tactic: "Credential Access" },
  "T1003.006": { name: "DCSync", tactic: "Credential Access" },
  "T1003.008": { name: "/etc/passwd and /etc/shadow", tactic: "Credential Access" },
  "T1005": { name: "Data from Local System", tactic: "Collection" },
  "T1006": { name: "Direct Volume Access", tactic: "Defense Evasion" },
  "T1007": { name: "System Service Discovery", tactic: "Discovery" },
  "T1008": { name: "Fallback Channels", tactic: "Command and Control" },
  "T1010": { name: "Application Window Discovery", tactic: "Discovery" },
  "T1011": { name: "Exfiltration Over Other Network Medium", tactic: "Exfiltration" },
  "T1012": { name: "Query Registry", tactic: "Discovery" },
  "T1014": { name: "Rootkit", tactic: "Defense Evasion" },
  "T1016": { name: "System Network Configuration Discovery", tactic: "Discovery" },
  "T1016.001": { name: "Internet Connection Discovery", tactic: "Discovery" },
  "T1020": { name: "Automated Exfiltration", tactic: "Exfiltration" },
  "T1020.001": { name: "Traffic Duplication", tactic: "Exfiltration" },
  "T1021.003": { name: "Distributed Component Object Model", tactic: "Lateral Movement" },
  "T1021.004": { name: "SSH", tactic: "Lateral Movement" },
  "T1021.005": { name: "VNC", tactic: "Lateral Movement" },
  "T1021.007": { name: "Cloud Services", tactic: "Lateral Movement" },
  "T1025": { name: "Data from Removable Media", tactic: "Collection" },
  "T1027.001": { name: "Binary Padding", tactic: "Defense Evasion" },
  "T1027.002": { name: "Software Packing", tactic: "Defense Evasion" },
  "T1027.003": { name: "Steganography", tactic: "Defense Evasion" },
  "T1027.004": { name: "Compile After Delivery", tactic: "Defense Evasion" },
  "T1027.005": { name: "Indicator Removal from Tools", tactic: "Defense Evasion" },
  "T1027.009": { name: "Embedded Payloads", tactic: "Defense Evasion" },
  "T1027.011": { name: "Fileless Storage", tactic: "Defense Evasion" },
  "T1027.013": { name: "Encrypted/Encoded File", tactic: "Defense Evasion" },
  "T1030": { name: "Data Transfer Size Limits", tactic: "Exfiltration" },
  "T1033": { name: "System Owner/User Discovery", tactic: "Discovery" },
  "T1036.002": { name: "Right-to-Left Override", tactic: "Defense Evasion" },
  "T1036.003": { name: "Rename Legitimate Utilities", tactic: "Defense Evasion" },
  "T1036.004": { name: "Masquerade Task or Service", tactic: "Defense Evasion" },
  "T1036.006": { name: "Space after Filename", tactic: "Defense Evasion" },
  "T1036.007": { name: "Double File Extension", tactic: "Defense Evasion" },
  "T1036.008": { name: "Masquerade File Type", tactic: "Defense Evasion" },
  "T1036.009": { name: "Break Process Trees", tactic: "Defense Evasion" },
  "T1037.001": { name: "Logon Script (Windows)", tactic: "Persistence" },
  "T1037.002": { name: "Login Hook", tactic: "Persistence" },
  "T1037.004": { name: "RC Scripts", tactic: "Persistence" },
  "T1037.005": { name: "Startup Items", tactic: "Persistence" },
  "T1039": { name: "Data from Network Shared Drive", tactic: "Collection" },
  "T1040": { name: "Network Sniffing", tactic: "Credential Access" },
  "T1048.001": { name: "Exfiltration Over Symmetric Encrypted Non-C2 Protocol", tactic: "Exfiltration" },
  "T1048.002": { name: "Exfiltration Over Asymmetric Encrypted Non-C2 Protocol", tactic: "Exfiltration" },
  "T1048.003": { name: "Exfiltration Over Unencrypted Non-C2 Protocol", tactic: "Exfiltration" },
  "T1049": { name: "System Network Connections Discovery", tactic: "Discovery" },
  "T1052": { name: "Exfiltration Over Physical Medium", tactic: "Exfiltration" },
  "T1053.002": { name: "At", tactic: "Execution" },
  "T1053.003": { name: "Cron", tactic: "Execution" },
  "T1053.006": { name: "Systemd Timers", tactic: "Execution" },
  "T1053.007": { name: "Container Orchestration Job", tactic: "Execution" },
  "T1055.001": { name: "Dynamic-link Library Injection", tactic: "Privilege Escalation" },
  "T1055.002": { name: "Portable Executable Injection", tactic: "Privilege Escalation" },
  "T1055.003": { name: "Thread Execution Hijacking", tactic: "Privilege Escalation" },
  "T1055.004": { name: "Asynchronous Procedure Call", tactic: "Privilege Escalation" },
  "T1055.008": { name: "Ptrace System Calls", tactic: "Privilege Escalation" },
  "T1055.009": { name: "Proc Memory", tactic: "Privilege Escalation" },
  "T1055.011": { name: "Extra Window Memory Injection", tactic: "Privilege Escalation" },
  "T1055.012": { name: "Process Hollowing", tactic: "Privilege Escalation" },
  "T1055.013": { name: "Process Doppelgänging", tactic: "Privilege Escalation" },
  "T1056": { name: "Input Capture", tactic: "Collection" },
  "T1056.001": { name: "Keylogging", tactic: "Collection" },
  "T1056.002": { name: "GUI Input Capture", tactic: "Collection" },
  "T1056.004": { name: "Credential API Hooking", tactic: "Collection" },
  "T1057": { name: "Process Discovery", tactic: "Discovery" },
  "T1059.002": { name: "AppleScript", tactic: "Execution" },
  "T1059.004": { name: "Unix Shell", tactic: "Execution" },
  "T1059.005": { name: "Visual Basic", tactic: "Execution" },
  "T1059.006": { name: "Python", tactic: "Execution" },
  "T1059.007": { name: "JavaScript", tactic: "Execution" },
  "T1059.009": { name: "Cloud API", tactic: "Execution" },
  "T1059.012": { name: "Hypervisor CLI", tactic: "Execution" },
  "T1059.013": { name: "Container CLI/API", tactic: "Execution" },
  "T1069": { name: "Permission Groups Discovery", tactic: "Discovery" },
  "T1069.001": { name: "Local Groups", tactic: "Discovery" },
  "T1069.002": { name: "Domain Groups", tactic: "Discovery" },
  "T1069.003": { name: "Cloud Groups", tactic: "Discovery" },
  "T1070.003": { name: "Clear Command History", tactic: "Defense Evasion" },
  "T1070.004": { name: "File Deletion", tactic: "Defense Evasion" },
  "T1070.005": { name: "Network Share Connection Removal", tactic: "Defense Evasion" },
  "T1070.006": { name: "Timestomp", tactic: "Defense Evasion" },
  "T1070.008": { name: "Clear Mailbox Data", tactic: "Defense Evasion" },
  "T1071.002": { name: "File Transfer Protocols", tactic: "Command and Control" },
  "T1071.003": { name: "Mail Protocols", tactic: "Command and Control" },
  "T1072": { name: "Software Deployment Tools", tactic: "Execution" },
  "T1074": { name: "Data Staged", tactic: "Collection" },
  "T1074.001": { name: "Local Data Staging", tactic: "Collection" },
  "T1078.001": { name: "Default Accounts", tactic: "Persistence" },
  "T1078.002": { name: "Domain Accounts", tactic: "Persistence" },
  "T1078.003": { name: "Local Accounts", tactic: "Persistence" },
  "T1078.004": { name: "Cloud Accounts", tactic: "Persistence" },
  "T1082": { name: "System Information Discovery", tactic: "Discovery" },
  "T1083": { name: "File and Directory Discovery", tactic: "Discovery" },
  "T1087.001": { name: "Local Account", tactic: "Discovery" },
  "T1087.004": { name: "Cloud Account", tactic: "Discovery" },
  "T1090.001": { name: "Internal Proxy", tactic: "Command and Control" },
  "T1090.002": { name: "External Proxy", tactic: "Command and Control" },
  "T1090.003": { name: "Multi-hop Proxy", tactic: "Command and Control" },
  "T1090.004": { name: "Domain Fronting", tactic: "Command and Control" },
  "T1091": { name: "Replication Through Removable Media", tactic: "Lateral Movement" },
  "T1095": { name: "Non-Application Layer Protocol", tactic: "Command and Control" },
  "T1098.002": { name: "Additional Email Delegate Permissions", tactic: "Persistence" },
  "T1098.004": { name: "SSH Authorized Keys", tactic: "Persistence" },
  "T1098.005": { name: "Device Registration", tactic: "Persistence" },
  "T1102.001": { name: "Dead Drop Resolver", tactic: "Command and Control" },
  "T1102.002": { name: "Bidirectional Communication", tactic: "Command and Control" },
  "T1102.003": { name: "One-Way Communication", tactic: "Command and Control" },
  "T1106": { name: "Native API", tactic: "Execution" },
  "T1110.002": { name: "Password Cracking", tactic: "Credential Access" },
  "T1111": { name: "Multi-Factor Authentication Interception", tactic: "Credential Access" },
  "T1112": { name: "Modify Registry", tactic: "Persistence" },
  "T1113": { name: "Screen Capture", tactic: "Collection" },
  "T1114.001": { name: "Local Email Collection", tactic: "Collection" },
  "T1114.002": { name: "Remote Email Collection", tactic: "Collection" },
  "T1114.003": { name: "Email Forwarding Rule", tactic: "Collection" },
  "T1115": { name: "Clipboard Data", tactic: "Collection" },
  "T1120": { name: "Peripheral Device Discovery", tactic: "Discovery" },
  "T1123": { name: "Audio Capture", tactic: "Collection" },
  "T1124": { name: "System Time Discovery", tactic: "Discovery" },
  "T1125": { name: "Video Capture", tactic: "Collection" },
  "T1127": { name: "Trusted Developer Utilities Proxy Execution", tactic: "Execution" },
  "T1127.001": { name: "MSBuild", tactic: "Execution" },
  "T1129": { name: "Shared Modules", tactic: "Execution" },
  "T1132": { name: "Data Encoding", tactic: "Command and Control" },
  "T1132.001": { name: "Standard Encoding", tactic: "Command and Control" },
  "T1134.001": { name: "Token Impersonation/Theft", tactic: "Privilege Escalation" },
  "T1134.002": { name: "Create Process with Token", tactic: "Privilege Escalation" },
  "T1134.003": { name: "Make and Impersonate Token", tactic: "Privilege Escalation" },
  "T1134.004": { name: "Parent PID Spoofing", tactic: "Privilege Escalation" },
  "T1134.005": { name: "SID-History Injection", tactic: "Privilege Escalation" },
  "T1135": { name: "Network Share Discovery", tactic: "Discovery" },
  "T1136.001": { name: "Local Account", tactic: "Persistence" },
  "T1136.002": { name: "Domain Account", tactic: "Persistence" },
  "T1137": { name: "Office Application Startup", tactic: "Persistence" },
  "T1137.002": { name: "Office Test", tactic: "Persistence" },
  "T1137.003": { name: "Outlook Forms", tactic: "Persistence" },
  "T1137.006": { name: "Add-ins", tactic: "Persistence" },
  "T1176": { name: "Software Extensions", tactic: "Persistence" },
  "T1176.001": { name: "Browser Extensions", tactic: "Persistence" },
  "T1185": { name: "Browser Session Hijacking", tactic: "Collection" },
  "T1189": { name: "Drive-by Compromise", tactic: "Initial Access" },
  "T1195.001": { name: "Compromise Software Dependencies and Development Tools", tactic: "Initial Access" },
  "T1195.002": { name: "Compromise Software Supply Chain", tactic: "Initial Access" },
  "T1197": { name: "BITS Jobs", tactic: "Persistence" },
  "T1200": { name: "Hardware Additions", tactic: "Initial Access" },
  "T1201": { name: "Password Policy Discovery", tactic: "Discovery" },
  "T1202": { name: "Indirect Command Execution", tactic: "Defense Evasion" },
  "T1204.001": { name: "Malicious Link", tactic: "Execution" },
  "T1204.003": { name: "Malicious Image", tactic: "Execution" },
  "T1204.004": { name: "Malicious Copy and Paste", tactic: "Execution" },
  "T1205.001": { name: "Port Knocking", tactic: "Persistence" },
  "T1207": { name: "Rogue Domain Controller", tactic: "Defense Evasion" },
  "T1210": { name: "Exploitation of Remote Services", tactic: "Lateral Movement" },
  "T1211": { name: "Exploitation for Stealth", tactic: "Defense Evasion" },
  "T1212": { name: "Exploitation for Credential Access", tactic: "Credential Access" },
  "T1213": { name: "Data from Information Repositories", tactic: "Collection" },
  "T1213.002": { name: "Sharepoint", tactic: "Collection" },
  "T1213.003": { name: "Code Repositories", tactic: "Collection" },
  "T1213.006": { name: "Databases", tactic: "Collection" },
  "T1216": { name: "System Script Proxy Execution", tactic: "Defense Evasion" },
  "T1216.001": { name: "PubPrn", tactic: "Defense Evasion" },
  "T1217": { name: "Browser Information Discovery", tactic: "Discovery" },
  "T1218.001": { name: "Compiled HTML File", tactic: "Defense Evasion" },
  "T1218.002": { name: "Control Panel", tactic: "Defense Evasion" },
  "T1218.003": { name: "CMSTP", tactic: "Defense Evasion" },
  "T1218.004": { name: "InstallUtil", tactic: "Defense Evasion" },
  "T1218.005": { name: "Mshta", tactic: "Defense Evasion" },
  "T1218.007": { name: "Msiexec", tactic: "Defense Evasion" },
  "T1218.008": { name: "Odbcconf", tactic: "Defense Evasion" },
  "T1218.009": { name: "Regsvcs/Regasm", tactic: "Defense Evasion" },
  "T1218.010": { name: "Regsvr32", tactic: "Defense Evasion" },
  "T1218.012": { name: "Verclsid", tactic: "Defense Evasion" },
  "T1218.013": { name: "Mavinject", tactic: "Defense Evasion" },
  "T1218.014": { name: "MMC", tactic: "Defense Evasion" },
  "T1219": { name: "Remote Access Tools", tactic: "Command and Control" },
  "T1219.002": { name: "Remote Desktop Software", tactic: "Command and Control" },
  "T1220": { name: "XSL Script Processing", tactic: "Defense Evasion" },
  "T1221": { name: "Template Injection", tactic: "Defense Evasion" },
  "T1222": { name: "File and Directory Permissions Modification", tactic: "Defense Evasion" },
  "T1222.001": { name: "Windows Permissions", tactic: "Defense Evasion" },
  "T1222.002": { name: "Linux and Mac Permissions", tactic: "Defense Evasion" },
  "T1404": { name: "Exploitation for Privilege Escalation", tactic: "Privilege Escalation" },
  "T1406": { name: "Obfuscated Files or Information", tactic: "Defense Evasion" },
  "T1409": { name: "Stored Application Data", tactic: "Collection" },
  "T1414": { name: "Clipboard Data", tactic: "Collection" },
  "T1417": { name: "Input Capture", tactic: "Collection" },
  "T1418": { name: "Software Discovery", tactic: "Discovery" },
  "T1422": { name: "System Network Configuration Discovery", tactic: "Discovery" },
  "T1423": { name: "Network Service Scanning", tactic: "Discovery" },
  "T1424": { name: "Process Discovery", tactic: "Discovery" },
  "T1428": { name: "Exploitation of Remote Services", tactic: "Lateral Movement" },
  "T1429": { name: "Audio Capture", tactic: "Collection" },
  "T1430": { name: "Location Tracking", tactic: "Collection" },
  "T1437": { name: "Application Layer Protocol", tactic: "Command and Control" },
  "T1456": { name: "Drive-By Compromise", tactic: "Initial Access" },
  "T1471": { name: "Data Encrypted for Impact", tactic: "Impact" },
  "T1474": { name: "Supply Chain Compromise", tactic: "Initial Access" },
  "T1480": { name: "Execution Guardrails", tactic: "Defense Evasion" },
  "T1481": { name: "Web Service", tactic: "Command and Control" },
  "T1482": { name: "Domain Trust Discovery", tactic: "Discovery" },
  "T1484": { name: "Domain or Tenant Policy Modification", tactic: "Privilege Escalation" },
  "T1484.001": { name: "Group Policy Modification", tactic: "Privilege Escalation" },
  "T1484.002": { name: "Trust Modification", tactic: "Privilege Escalation" },
  "T1485.001": { name: "Lifecycle-Triggered Deletion", tactic: "Impact" },
  "T1491": { name: "Defacement", tactic: "Impact" },
  "T1491.001": { name: "Internal Defacement", tactic: "Impact" },
  "T1495": { name: "Firmware Corruption", tactic: "Impact" },
  "T1496": { name: "Resource Hijacking", tactic: "Impact" },
  "T1497": { name: "Virtualization/Sandbox Evasion", tactic: "Discovery" },
  "T1497.001": { name: "System Checks", tactic: "Discovery" },
  "T1497.003": { name: "Time Based Checks", tactic: "Discovery" },
  "T1498": { name: "Network Denial of Service", tactic: "Impact" },
  "T1498.002": { name: "Reflection Amplification", tactic: "Impact" },
  "T1499": { name: "Endpoint Denial of Service", tactic: "Impact" },
  "T1499.001": { name: "OS Exhaustion Flood", tactic: "Impact" },
  "T1499.004": { name: "Application or System Exploitation", tactic: "Impact" },
  "T1505.001": { name: "SQL Stored Procedures", tactic: "Persistence" },
  "T1505.002": { name: "Transport Agent", tactic: "Persistence" },
  "T1505.004": { name: "IIS Components", tactic: "Persistence" },
  "T1505.005": { name: "Terminal Services DLL", tactic: "Persistence" },
  "T1505.006": { name: "vSphere Installation Bundles", tactic: "Persistence" },
  "T1509": { name: "Non-Standard Port", tactic: "Command and Control" },
  "T1512": { name: "Video Capture", tactic: "Collection" },
  "T1513": { name: "Screen Capture", tactic: "Collection" },
  "T1516": { name: "Input Injection", tactic: "Defense Evasion" },
  "T1517": { name: "Access Notifications", tactic: "Collection" },
  "T1525": { name: "Implant Internal Image", tactic: "Persistence" },
  "T1526": { name: "Cloud Service Discovery", tactic: "Discovery" },
  "T1529": { name: "System Shutdown/Reboot", tactic: "Impact" },
  "T1531": { name: "Account Access Removal", tactic: "Impact" },
  "T1532": { name: "Archive Collected Data", tactic: "Collection" },
  "T1534": { name: "Internal Spearphishing", tactic: "Lateral Movement" },
  "T1535": { name: "Unused/Unsupported Cloud Regions", tactic: "Defense Evasion" },
  "T1537": { name: "Transfer Data to Cloud Account", tactic: "Exfiltration" },
  "T1538": { name: "Cloud Service Dashboard", tactic: "Discovery" },
  "T1539": { name: "Steal Web Session Cookie", tactic: "Credential Access" },
  "T1541": { name: "Foreground Persistence", tactic: "Defense Evasion" },
  "T1542": { name: "Pre-OS Boot", tactic: "Persistence" },
  "T1542.001": { name: "System Firmware", tactic: "Persistence" },
  "T1542.003": { name: "Bootkit", tactic: "Persistence" },
  "T1542.005": { name: "TFTP Boot", tactic: "Persistence" },
  "T1543.001": { name: "Launch Agent", tactic: "Persistence" },
  "T1543.002": { name: "Systemd Service", tactic: "Persistence" },
  "T1543.004": { name: "Launch Daemon", tactic: "Persistence" },
  "T1544": { name: "Ingress Tool Transfer", tactic: "Command and Control" },
  "T1546": { name: "Event Triggered Execution", tactic: "Privilege Escalation" },
  "T1546.001": { name: "Change Default File Association", tactic: "Privilege Escalation" },
  "T1546.002": { name: "Screensaver", tactic: "Privilege Escalation" },
  "T1546.003": { name: "Windows Management Instrumentation Event Subscription", tactic: "Privilege Escalation" },
  "T1546.004": { name: "Unix Shell Configuration Modification", tactic: "Privilege Escalation" },
  "T1546.007": { name: "Netsh Helper DLL", tactic: "Privilege Escalation" },
  "T1546.008": { name: "Accessibility Features", tactic: "Privilege Escalation" },
  "T1546.009": { name: "AppCert DLLs", tactic: "Privilege Escalation" },
  "T1546.010": { name: "AppInit DLLs", tactic: "Privilege Escalation" },
  "T1546.011": { name: "Application Shimming", tactic: "Privilege Escalation" },
  "T1546.012": { name: "Image File Execution Options Injection", tactic: "Privilege Escalation" },
  "T1546.013": { name: "PowerShell Profile", tactic: "Privilege Escalation" },
  "T1546.014": { name: "Emond", tactic: "Privilege Escalation" },
  "T1546.015": { name: "Component Object Model Hijacking", tactic: "Privilege Escalation" },
  "T1547.002": { name: "Authentication Package", tactic: "Persistence" },
  "T1547.003": { name: "Time Providers", tactic: "Persistence" },
  "T1547.004": { name: "Winlogon Helper DLL", tactic: "Persistence" },
  "T1547.005": { name: "Security Support Provider", tactic: "Persistence" },
  "T1547.006": { name: "Kernel Modules and Extensions", tactic: "Persistence" },
  "T1547.008": { name: "LSASS Driver", tactic: "Persistence" },
  "T1547.009": { name: "Shortcut Modification", tactic: "Persistence" },
  "T1547.010": { name: "Port Monitors", tactic: "Persistence" },
  "T1547.012": { name: "Print Processors", tactic: "Persistence" },
  "T1547.014": { name: "Active Setup", tactic: "Persistence" },
  "T1547.015": { name: "Login Items", tactic: "Persistence" },
  "T1548.001": { name: "Setuid and Setgid", tactic: "Privilege Escalation" },
  "T1548.003": { name: "Sudo and Sudo Caching", tactic: "Privilege Escalation" },
  "T1550.001": { name: "Application Access Token", tactic: "Lateral Movement" },
  "T1550.004": { name: "Web Session Cookie", tactic: "Lateral Movement" },
  "T1552.002": { name: "Credentials in Registry", tactic: "Credential Access" },
  "T1552.003": { name: "Shell History", tactic: "Credential Access" },
  "T1552.004": { name: "Private Keys", tactic: "Credential Access" },
  "T1552.005": { name: "Cloud Instance Metadata API", tactic: "Credential Access" },
  "T1552.006": { name: "Group Policy Preferences", tactic: "Credential Access" },
  "T1552.007": { name: "Container API", tactic: "Credential Access" },
  "T1553": { name: "Subvert Trust Controls", tactic: "Defense Evasion" },
  "T1553.001": { name: "Gatekeeper Bypass", tactic: "Defense Evasion" },
  "T1553.002": { name: "Code Signing", tactic: "Defense Evasion" },
  "T1553.003": { name: "SIP and Trust Provider Hijacking", tactic: "Defense Evasion" },
  "T1553.004": { name: "Install Root Certificate", tactic: "Defense Evasion" },
  "T1553.005": { name: "Mark-of-the-Web Bypass", tactic: "Defense Evasion" },
  "T1554": { name: "Compromise Host Software Binary", tactic: "Persistence" },
  "T1555.001": { name: "Keychain", tactic: "Credential Access" },
  "T1555.004": { name: "Windows Credential Manager", tactic: "Credential Access" },
  "T1555.005": { name: "Password Managers", tactic: "Credential Access" },
  "T1556.002": { name: "Password Filter DLL", tactic: "Persistence" },
  "T1556.004": { name: "Network Device Authentication", tactic: "Persistence" },
  "T1556.006": { name: "Multi-Factor Authentication", tactic: "Persistence" },
  "T1557": { name: "Adversary-in-the-Middle", tactic: "Credential Access" },
  "T1557.001": { name: "Name Resolution Poisoning and SMB Relay", tactic: "Credential Access" },
  "T1557.002": { name: "ARP Cache Poisoning", tactic: "Credential Access" },
  "T1557.003": { name: "DHCP Spoofing", tactic: "Credential Access" },
  "T1558.001": { name: "Golden Ticket", tactic: "Credential Access" },
  "T1558.002": { name: "Silver Ticket", tactic: "Credential Access" },
  "T1559": { name: "Inter-Process Communication", tactic: "Execution" },
  "T1559.001": { name: "Component Object Model", tactic: "Execution" },
  "T1559.002": { name: "Dynamic Data Exchange", tactic: "Execution" },
  "T1560": { name: "Archive Collected Data", tactic: "Collection" },
  "T1560.001": { name: "Archive via Utility", tactic: "Collection" },
  "T1561": { name: "Disk Wipe", tactic: "Impact" },
  "T1561.001": { name: "Disk Content Wipe", tactic: "Impact" },
  "T1561.002": { name: "Disk Structure Wipe", tactic: "Impact" },
  "T1562.002": { name: "Disable or Modify Windows Event Log", tactic: "Defense Evasion" },
  "T1562.006": { name: "Disable or Modify Tools", tactic: "Defense Evasion" },
  "T1562.007": { name: "Cloud Firewall", tactic: "Defense Evasion" },
  "T1562.008": { name: "Disable or Modify Cloud Log", tactic: "Defense Evasion" },
  "T1563.002": { name: "RDP Hijacking", tactic: "Lateral Movement" },
  "T1564": { name: "Hide Artifacts", tactic: "Defense Evasion" },
  "T1564.001": { name: "Hidden Files and Directories", tactic: "Defense Evasion" },
  "T1564.002": { name: "Hidden Users", tactic: "Defense Evasion" },
  "T1564.003": { name: "Hidden Window", tactic: "Defense Evasion" },
  "T1564.004": { name: "NTFS File Attributes", tactic: "Defense Evasion" },
  "T1564.006": { name: "Run Virtual Instance", tactic: "Defense Evasion" },
  "T1564.008": { name: "Email Hiding Rules", tactic: "Defense Evasion" },
  "T1565": { name: "Data Manipulation", tactic: "Impact" },
  "T1565.001": { name: "Stored Data Manipulation", tactic: "Impact" },
  "T1565.002": { name: "Transmitted Data Manipulation", tactic: "Impact" },
  "T1566.003": { name: "Spearphishing via Service", tactic: "Initial Access" },
  "T1567.001": { name: "Exfiltration to Code Repository", tactic: "Exfiltration" },
  "T1568": { name: "Dynamic Resolution", tactic: "Command and Control" },
  "T1568.001": { name: "Fast Flux DNS", tactic: "Command and Control" },
  "T1568.002": { name: "Domain Generation Algorithms", tactic: "Command and Control" },
  "T1569.001": { name: "Launchctl", tactic: "Execution" },
  "T1571": { name: "Non-Standard Port", tactic: "Command and Control" },
  "T1573": { name: "Encrypted Channel", tactic: "Command and Control" },
  "T1573.001": { name: "Symmetric Cryptography", tactic: "Command and Control" },
  "T1573.002": { name: "Asymmetric Cryptography", tactic: "Command and Control" },
  "T1574": { name: "Hijack Execution Flow", tactic: "Execution" },
  "T1574.001": { name: "DLL", tactic: "Execution" },
  "T1574.002": { name: "DLL", tactic: "Execution" },
  "T1574.004": { name: "Dylib Hijacking", tactic: "Execution" },
  "T1574.005": { name: "Executable Installer File Permissions Weakness", tactic: "Execution" },
  "T1574.006": { name: "Dynamic Linker Hijacking", tactic: "Execution" },
  "T1574.007": { name: "Path Interception by PATH Environment Variable", tactic: "Execution" },
  "T1574.008": { name: "Path Interception by Search Order Hijacking", tactic: "Execution" },
  "T1574.009": { name: "Path Interception by Unquoted Path", tactic: "Execution" },
  "T1574.011": { name: "Services Registry Permissions Weakness", tactic: "Execution" },
  "T1574.012": { name: "COR_PROFILER", tactic: "Execution" },
  "T1574.014": { name: "AppDomainManager", tactic: "Execution" },
  "T1578": { name: "Modify Cloud Compute Infrastructure", tactic: "Defense Evasion" },
  "T1578.002": { name: "Create Cloud Instance", tactic: "Defense Evasion" },
  "T1578.003": { name: "Delete Cloud Instance", tactic: "Defense Evasion" },
  "T1578.005": { name: "Modify Cloud Compute Configurations", tactic: "Defense Evasion" },
  "T1580": { name: "Cloud Infrastructure Discovery", tactic: "Discovery" },
  "T1582": { name: "SMS Control", tactic: "Impact" },
  "T1583": { name: "Acquire Infrastructure", tactic: "Resource Development" },
  "T1583.001": { name: "Domains", tactic: "Resource Development" },
  "T1583.006": { name: "Web Services", tactic: "Resource Development" },
  "T1584": { name: "Compromise Infrastructure", tactic: "Resource Development" },
  "T1584.002": { name: "DNS Server", tactic: "Resource Development" },
  "T1585": { name: "Establish Accounts", tactic: "Resource Development" },
  "T1585.001": { name: "Social Media Accounts", tactic: "Resource Development" },
  "T1585.002": { name: "Email Accounts", tactic: "Resource Development" },
  "T1585.003": { name: "Cloud Accounts", tactic: "Resource Development" },
  "T1586": { name: "Compromise Accounts", tactic: "Resource Development" },
  "T1586.002": { name: "Email Accounts", tactic: "Resource Development" },
  "T1586.003": { name: "Cloud Accounts", tactic: "Resource Development" },
  "T1587": { name: "Develop Capabilities", tactic: "Resource Development" },
  "T1587.001": { name: "Malware", tactic: "Resource Development" },
  "T1587.002": { name: "Code Signing Certificates", tactic: "Resource Development" },
  "T1587.003": { name: "Digital Certificates", tactic: "Resource Development" },
  "T1588": { name: "Obtain Capabilities", tactic: "Resource Development" },
  "T1588.001": { name: "Malware", tactic: "Resource Development" },
  "T1588.002": { name: "Tool", tactic: "Resource Development" },
  "T1588.004": { name: "Digital Certificates", tactic: "Resource Development" },
  "T1589.001": { name: "Credentials", tactic: "Reconnaissance" },
  "T1589.002": { name: "Email Addresses", tactic: "Reconnaissance" },
  "T1589.003": { name: "Employee Names", tactic: "Reconnaissance" },
  "T1590.001": { name: "Domain Properties", tactic: "Reconnaissance" },
  "T1590.002": { name: "DNS", tactic: "Reconnaissance" },
  "T1590.005": { name: "IP Addresses", tactic: "Reconnaissance" },
  "T1591": { name: "Gather Victim Org Information", tactic: "Reconnaissance" },
  "T1591.002": { name: "Business Relationships", tactic: "Reconnaissance" },
  "T1591.004": { name: "Identify Roles", tactic: "Reconnaissance" },
  "T1592": { name: "Gather Victim Host Information", tactic: "Reconnaissance" },
  "T1592.001": { name: "Hardware", tactic: "Reconnaissance" },
  "T1592.002": { name: "Software", tactic: "Reconnaissance" },
  "T1592.004": { name: "Client Configurations", tactic: "Reconnaissance" },
  "T1593": { name: "Search Open Websites/Domains", tactic: "Reconnaissance" },
  "T1593.003": { name: "Code Repositories", tactic: "Reconnaissance" },
  "T1595.002": { name: "Vulnerability Scanning", tactic: "Reconnaissance" },
  "T1596": { name: "Search Open Technical Databases", tactic: "Reconnaissance" },
  "T1598": { name: "Phishing for Information", tactic: "Reconnaissance" },
  "T1598.002": { name: "Spearphishing Attachment", tactic: "Reconnaissance" },
  "T1598.003": { name: "Spearphishing Link", tactic: "Reconnaissance" },
  "T1599": { name: "Network Boundary Bridging", tactic: "Defense Evasion" },
  "T1599.001": { name: "Network Address Translation Traversal", tactic: "Defense Evasion" },
  "T1601.001": { name: "Patch System Image", tactic: "Defense Evasion" },
  "T1606": { name: "Forge Web Credentials", tactic: "Credential Access" },
  "T1606.001": { name: "Web Cookies", tactic: "Credential Access" },
  "T1608": { name: "Stage Capabilities", tactic: "Resource Development" },
  "T1608.001": { name: "Upload Malware", tactic: "Resource Development" },
  "T1608.002": { name: "Upload Tool", tactic: "Resource Development" },
  "T1608.003": { name: "Install Digital Certificate", tactic: "Resource Development" },
  "T1609": { name: "Container Administration Command", tactic: "Execution" },
  "T1610": { name: "Deploy Container", tactic: "Execution" },
  "T1613": { name: "Container and Resource Discovery", tactic: "Discovery" },
  "T1614.001": { name: "System Language Discovery", tactic: "Discovery" },
  "T1615": { name: "Group Policy Discovery", tactic: "Discovery" },
  "T1616": { name: "Call Control", tactic: "Collection" },
  "T1617": { name: "Hooking", tactic: "Defense Evasion" },
  "T1619": { name: "Cloud Storage Object Discovery", tactic: "Discovery" },
  "T1622": { name: "Debugger Evasion", tactic: "Discovery" },
  "T1623": { name: "Command and Scripting Interpreter", tactic: "Execution" },
  "T1624": { name: "Event Triggered Execution", tactic: "Persistence" },
  "T1625": { name: "Hijack Execution Flow", tactic: "Persistence" },
  "T1626": { name: "Abuse Elevation Control Mechanism", tactic: "Privilege Escalation" },
  "T1627": { name: "Execution Guardrails", tactic: "Defense Evasion" },
  "T1628": { name: "Hide Artifacts", tactic: "Defense Evasion" },
  "T1629": { name: "Impair Defenses", tactic: "Defense Evasion" },
  "T1630": { name: "Indicator Removal on Host", tactic: "Defense Evasion" },
  "T1631": { name: "Process Injection", tactic: "Defense Evasion" },
  "T1633": { name: "Virtualization/Sandbox Evasion", tactic: "Defense Evasion" },
  "T1634": { name: "Credentials from Password Store", tactic: "Credential Access" },
  "T1635": { name: "Steal Application Access Token", tactic: "Credential Access" },
  "T1636": { name: "Protected User Data", tactic: "Collection" },
  "T1638": { name: "Adversary-in-the-Middle", tactic: "Collection" },
  "T1639": { name: "Exfiltration Over Alternative Protocol", tactic: "Exfiltration" },
  "T1640": { name: "Account Access Removal", tactic: "Impact" },
  "T1641": { name: "Data Manipulation", tactic: "Impact" },
  "T1642": { name: "Endpoint Denial of Service", tactic: "Impact" },
  "T1643": { name: "Generate Traffic from Victim", tactic: "Impact" },
  "T1645": { name: "Compromise Client Software Binary", tactic: "Persistence" },
  "T1646": { name: "Exfiltration Over C2 Channel", tactic: "Exfiltration" },
  "T1647": { name: "Plist File Modification", tactic: "Defense Evasion" },
  "T1649": { name: "Steal or Forge Authentication Certificates", tactic: "Credential Access" },
  "T1651": { name: "Cloud Administration Command", tactic: "Execution" },
  "T1653": { name: "Power Settings", tactic: "Persistence" },
  "T1654": { name: "Log Enumeration", tactic: "Discovery" },
  "T1655": { name: "Masquerading", tactic: "Defense Evasion" },
  "T1657": { name: "Financial Theft", tactic: "Impact" },
  "T1659": { name: "Content Injection", tactic: "Initial Access" },
  "T1660": { name: "Phishing", tactic: "Initial Access" },
  "T1664": { name: "Exploitation for Initial Access", tactic: "Initial Access" },
  "T1673": { name: "Virtual Machine Discovery", tactic: "Discovery" },
  "T1685": { name: "Disable or Modify Tools", tactic: "Defense Evasion" },
  "T1685.001": { name: "Disable or Modify Windows Event Log", tactic: "Defense Evasion" },
  "T1685.002": { name: "Disable or Modify Cloud Log", tactic: "Defense Evasion" },
  "T1685.004": { name: "Disable or Modify Linux Audit System Log", tactic: "Defense Evasion" },
  "T1685.005": { name: "Clear Windows Event Logs", tactic: "Defense Evasion" },
  "T1685.006": { name: "Clear Linux or Mac System Logs", tactic: "Defense Evasion" },
  "T1686": { name: "Disable or Modify System Firewall", tactic: "Defense Evasion" },
  "T1686.001": { name: "Cloud Firewall", tactic: "Defense Evasion" },
  "T1686.003": { name: "Windows Host Firewall", tactic: "Defense Evasion" },
  "T1688": { name: "Safe Mode Boot", tactic: "Defense Evasion" },
  "T1689": { name: "Downgrade Attack", tactic: "Defense Evasion" },
  "T1690": { name: "Prevent Command History Logging", tactic: "Defense Evasion" },
};
